### ISSUE TITLE
1.0.0-rc.1 implementation issues

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#260]
As I'm currently implementing 1.0.0-rc.1 for GEE, here's a list of what came up:

## General 
- [x] 1. The CHANGELOG is not complete. Fixed in 1e67bd017eb83362a5197e40599ecf6b0f1456d3
- [x] 2. It is not clear how back-end should react on a limit parameter if they don't support pagination (error vs. return the full list). Fixed in f1a7bb739f16146f6857755300be4a3c262b51f9
- [x] 3. The JSON Schema for process graph validation is invalid (used `from_argument` instead of `from_parameter`). Fixed in 1c3e4ed9876bbf9bd0c7e7df9e9213a385f24550
- [x] 4. Update STAC from 0.9.0 RC1 to 0.9.0 (RC2) if required, there were some minor changes.
- [x] 5. `offset` parameter is missing from logs endpoints. See PR #263 
- [x] 6. Clarify which instance is the default instance to connect to, Fixed in 2856cd5ea91f32d35fbd538e4b6a0411e70987fe, see also issue #259. 

## Related to process graphs (user-defined processes)

- [x] A. Sending process graphs to /services, /jobs and /result is lacking the default values from the parameters that are available in /process_graphs. This may lead to issues during execution when user hasn't specified the parameters. See PR #262
- [x] B. `GET /process_graphs`: Field `id` is not required for the processes. Fixed in 05bc778025716e993ce3e1765cf15f4344e5b46a
- [x] C. `POST /process_graphs` is not following REST. It should be `PUT /process_graphs/{process_graph_id}` as we actually set the id ourself. From docs it's also not 100% clear whether the process graph id (e.g. in the path) is the same as a process id. See PR #261 
- [x] D. `PATCH /process_graphs/{process_graph_id}` allows to change the id, but the behavior afterwards is unclear. In theory the path must change. I tend to forbid changing the ID. See PR #261
- [x] E. Usually in responses like `GET /jobs/{job_id}` or `GET /services/{service_id}` most (all?) optional fields can be set to `null`, which makes implementation a bit easier. For the process graphs at `/process_graphs` none of the fields can be set to null and so they must actually be missing from the response if no data is available. That's more difficult to implement, but aligned with `/processes`. Should we introduce nullable for some/all fields in `/process_graph`s and/or `/processes`? For more information see issue #264.
- [x] F. Related to E: As you can't set `null` in `PATCH /process_graphs/{process_graph_id}` you can't easily "reset" fields. For example, you can only remove the description by sending an empty string. For parameters you'd need to send am empty object, but that means "no parameters" where as not having parameters at all means the parameters are simply unknown/unspecified, but there may be some. See PR #261

We may head for a quick 1.0.0-rc.2 as I guess there wasn't much work put into 1.0.0-rc.1 implementations yet.

**Comment by m-mohr** [comment]
Proposals:
* For A, C, D and F: `POST /process_graphs` and `PATCH /process_graphs/:id` with a single endpoint `PUT /process_graphs/:id`. id can't be changed as it's part of the path.
* For E:  Allow null in optional fields in /process_graphs and /processes.
* For 2: Back-ends return the full list if pagination is not supported.

Will put up a PR shortly.

@jdries @soxofaan @lforesta @aljacob @kempenep @flahn
